<script setup lang="ts">
import type { SummaryFormat } from "../api/peptrack";

interface SummaryFormModel {
  title: string;
  content: string;
  format: SummaryFormat;
}

const props = defineProps<{
  form: SummaryFormModel;
  summarizing: boolean;
  summaryOutput: string | null;
  summaryProvider: string | null;
}>();

const emit = defineEmits<{
  summarize: [];
}>();

function handleSubmit() {
  emit("summarize");
}
</script>

<template>
  <section class="panel">
    <div class="panel-header">
      <div>
        <h2>AI Literature Summary</h2>
        <p class="muted">
          Uses local Codex CLI by default; falls back to Claude CLI (claude-haiku-4-5).
        </p>
      </div>
    </div>
    <form class="form-stack" @submit.prevent="handleSubmit">
      <label>
        Title
        <input v-model="props.form.title" type="text" placeholder="Paper title" />
      </label>
      <label>
        Format
        <select v-model="props.form.format">
          <option value="Markdown">Markdown</option>
          <option value="Json">JSON</option>
        </select>
      </label>
      <label>
        Content
        <textarea
          v-model="props.form.content"
          rows="6"
          placeholder="Paste abstract, key findings, or raw notes"
        />
      </label>
      <button class="primary" type="submit" :disabled="props.summarizing">
        {{ props.summarizing ? "Summarizing..." : "Summarize" }}
      </button>
    </form>

    <div v-if="props.summaryOutput" class="summary-output">
      <div class="summary-meta">
        Generated by: {{ props.summaryProvider }}
      </div>
      <pre>{{ props.summaryOutput }}</pre>
    </div>
  </section>
</template>
