<template>
  <section class="ai-summary-panel">
    <div class="panel-header">
      <div>
        <h2>🤖 AI Summary Helper</h2>
        <p class="muted">Transform research papers into simple summaries</p>
      </div>
      <div class="header-actions">
        <button
          v-if="summaryHistory.length > 0"
          @click="showHistory = !showHistory"
          class="ghost-btn"
        >
          📚 History ({{ summaryHistory.length }})
        </button>
      </div>
    </div>

    <!-- Summary History Modal -->
    <div v-if="showHistory" class="history-modal-overlay" @click="showHistory = false">
      <div class="history-modal" @click.stop>
        <div class="modal-header">
          <h3>📚 Summary History</h3>
          <button @click="showHistory = false" class="close-btn">✕</button>
        </div>
        <div class="history-list">
          <div
            v-for="entry in summaryHistory"
            :key="entry.id"
            class="history-entry"
          >
            <div class="history-entry-header">
              <h4>{{ entry.title || 'Untitled Summary' }}</h4>
              <div class="entry-meta">
                <span class="badge">{{ entry.format }}</span>
                <span class="badge">{{ entry.provider }}</span>
                <span class="date">{{ formatDate(entry.created_at) }}</span>
              </div>
            </div>
            <div class="history-entry-actions">
              <button @click="loadHistoryEntry(entry)" class="small-btn">
                📄 Load
              </button>
              <button @click="copyToClipboard(entry.summary_output)" class="small-btn">
                📋 Copy
              </button>
              <button @click="deleteHistoryEntry(entry.id)" class="small-btn danger">
                🗑️ Delete
              </button>
            </div>
          </div>
          <div v-if="summaryHistory.length === 0" class="no-history">
            No summary history yet. Create your first summary!
          </div>
        </div>
      </div>
    </div>

    <!-- Main Form -->
    <form class="form-stack" @submit.prevent="handleSubmit">
      <label>
        Paper Name (optional)
        <input
          v-model="formData.title"
          type="text"
          placeholder="e.g., BPC-157 Healing Study"
        />
      </label>

      <label>
        Paste Text Here
        <div class="textarea-wrapper">
          <textarea
            v-model="formData.content"
            rows="8"
            placeholder="Copy and paste text from the paper you want summarized..."
            @input="updateCharCount"
          />
          <div class="char-count" :class="{ warning: charCount > 10000 }">
            {{ charCount.toLocaleString() }} characters
            <span v-if="charCount > 10000" class="warning-text">
              (Very long - may take time)
            </span>
          </div>
        </div>
      </label>

      <div class="form-row">
        <label class="format-selector">
          Output Format
          <select v-model="formData.format">
            <option value="Markdown">📝 Markdown (structured)</option>
            <option value="Plain">📄 Plain Text</option>
            <option value="Bullets">• Bullet Points</option>
          </select>
        </label>

        <label class="style-selector">
          Summary Style
          <select v-model="summaryStyle">
            <option value="balanced">⚖️ Balanced</option>
            <option value="simple">🎯 Simple (ELI5)</option>
            <option value="technical">🔬 Technical</option>
            <option value="brief">⚡ Brief</option>
          </select>
        </label>
      </div>

      <button
        class="primary"
        type="submit"
        :disabled="props.summarizing || !formData.content.trim()"
      >
        {{
          props.summarizing
            ? "⏳ Creating Summary..."
            : "✨ Summarize This"
        }}
      </button>
    </form>

    <!-- Summary Output -->
    <div v-if="props.summaryOutput" class="summary-output">
      <div class="output-header">
        <h3>📝 Your Summary</h3>
        <div class="output-actions">
          <button @click="copyToClipboard(props.summaryOutput)" class="action-btn">
            📋 Copy
          </button>
          <button @click="exportSummary" class="action-btn">
            💾 Export
          </button>
          <button @click="regenerateSummary" class="action-btn" :disabled="props.summarizing">
            🔄 Regenerate
          </button>
        </div>
      </div>

      <div v-if="props.summaryProvider" class="provider-badge">
        Generated by: {{ props.summaryProvider }}
      </div>

      <!-- Render markdown or plain text -->
      <div v-if="formData.format === 'Markdown'" class="markdown-output" v-html="renderedMarkdown"></div>
      <pre v-else class="plain-output">{{ props.summaryOutput }}</pre>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { marked } from 'marked';
import type { SummaryFormat, SummaryHistory } from '../api/peptrack';
import { listSummaryHistory, deleteSummaryFromHistory, saveSummary } from '../api/peptrack';
import { showSuccessToast, showErrorToast } from '../utils/errorHandling';

interface SummaryFormModel {
  title: string;
  content: string;
  format: SummaryFormat;
}

const props = defineProps<{
  form: SummaryFormModel;
  summarizing: boolean;
  summaryOutput: string | null;
  summaryProvider: string | null;
}>();

const emit = defineEmits<{
  summarize: [];
  'update:title': [value: string];
  'update:content': [value: string];
  'update:format': [value: SummaryFormat];
}>();

// Local form state
const formData = ref<SummaryFormModel>({
  title: props.form.title,
  content: props.form.content,
  format: props.form.format,
});

const summaryStyle = ref<string>('balanced');
const charCount = ref(0);
const showHistory = ref(false);
const summaryHistory = ref<SummaryHistory[]>([]);

// Watch for external prop changes
watch(() => props.form, (newForm) => {
  formData.value = { ...newForm };
  updateCharCount();
}, { deep: true });

// Update parent when local form changes
watch(() => formData.value.title, (val) => emit('update:title', val));
watch(() => formData.value.content, (val) => emit('update:content', val));
watch(() => formData.value.format, (val) => emit('update:format', val as SummaryFormat));

const renderedMarkdown = computed(() => {
  if (!props.summaryOutput || formData.value.format !== 'Markdown') return '';
  return marked.parse(props.summaryOutput);
});

function updateCharCount() {
  charCount.value = formData.value.content.length;
}

function handleSubmit() {
  if (!formData.value.content.trim()) {
    showErrorToast('Please enter some text to summarize', { operation: 'summarize' });
    return;
  }

  // Append style instruction to content
  let contentWithStyle = formData.value.content;
  if (summaryStyle.value !== 'balanced') {
    const styleInstructions = {
      simple: '\n\nPlease explain this in simple terms that anyone can understand (ELI5 style).',
      technical: '\n\nPlease provide a technical summary with all important details and terminology.',
      brief: '\n\nPlease provide a very brief summary highlighting only the key points.',
    };
    contentWithStyle += styleInstructions[summaryStyle.value as keyof typeof styleInstructions] || '';
  }

  // Temporarily update content for summarization
  emit('update:content', contentWithStyle);
  emit('summarize');

  // Restore original content after a short delay
  setTimeout(() => {
    emit('update:content', formData.value.content);
  }, 100);
}

function regenerateSummary() {
  handleSubmit();
}

async function copyToClipboard(text: string) {
  try {
    await navigator.clipboard.writeText(text);
    showSuccessToast('Copied', 'Summary copied to clipboard');
  } catch (error) {
    showErrorToast(error, { operation: 'copy to clipboard' });
  }
}

function exportSummary() {
  if (!props.summaryOutput) return;

  const filename = `summary-${formData.value.title || 'untitled'}-${Date.now()}.txt`;
  const blob = new Blob([props.summaryOutput], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
  showSuccessToast('Exported', 'Summary exported successfully');
}

async function loadSummaryHistory() {
  try {
    summaryHistory.value = await listSummaryHistory(20);
  } catch (error) {
    showErrorToast(error, { operation: 'load summary history' });
  }
}

function loadHistoryEntry(entry: SummaryHistory) {
  formData.value.title = entry.title;
  formData.value.content = entry.original_content;
  formData.value.format = entry.format as SummaryFormat;

  emit('update:title', entry.title);
  emit('update:content', entry.original_content);
  emit('update:format', entry.format as SummaryFormat);

  showHistory.value = false;
  showSuccessToast('Loaded', 'Summary loaded from history');
}

async function deleteHistoryEntry(id: string) {
  if (!confirm('Delete this summary from history?')) return;

  try {
    await deleteSummaryFromHistory(id);
    await loadSummaryHistory();
    showSuccessToast('Deleted', 'Summary removed from history');
  } catch (error) {
    showErrorToast(error, { operation: 'delete summary' });
  }
}

function formatDate(dateStr: string): string {
  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString() + ' ' + date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  } catch {
    return dateStr;
  }
}

// Save summary to history when new summary is generated
watch(() => props.summaryOutput, async (newOutput) => {
  if (newOutput && props.summaryProvider && formData.value.content) {
    try {
      await saveSummary({
        title: formData.value.title || 'Untitled Summary',
        originalContent: formData.value.content,
        summaryOutput: newOutput,
        format: formData.value.format,
        provider: props.summaryProvider,
      });
      await loadSummaryHistory();
    } catch (error) {
      // Silent fail - don't disrupt user experience
      console.error('Failed to save summary history:', error);
    }
  }
});

onMounted(() => {
  updateCharCount();
  loadSummaryHistory();
});
</script>

<style scoped>
.ai-summary-panel {
  padding: 20px;
  max-width: 1000px;
  margin: 0 auto;
}

.panel-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 20px;
}

.panel-header h2 {
  margin: 0 0 4px 0;
  color: #2c3e50;
}

.muted {
  color: #666;
  font-size: 14px;
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.ghost-btn {
  padding: 8px 14px;
  border-radius: 6px;
  border: 1px solid #d1d5db;
  background: #fff;
  color: #374151;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.ghost-btn:hover {
  background: #f3f4f6;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.form-stack {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

label {
  display: flex;
  flex-direction: column;
  gap: 6px;
  font-weight: 600;
  font-size: 14px;
  color: #333;
}

input[type="text"],
textarea,
select {
  padding: 10px 12px;
  border: 2px solid #ddd;
  border-radius: 6px;
  font-size: 14px;
  font-family: inherit;
  transition: border-color 0.2s;
}

input[type="text"]:focus,
textarea:focus,
select:focus {
  outline: none;
  border-color: #3498db;
  box-shadow: 0 0 0 3px rgba(52, 152, 219, 0.1);
}

.textarea-wrapper {
  position: relative;
}

.char-count {
  position: absolute;
  bottom: 8px;
  right: 12px;
  font-size: 12px;
  color: #999;
  background: rgba(255, 255, 255, 0.9);
  padding: 4px 8px;
  border-radius: 4px;
  pointer-events: none;
}

.char-count.warning {
  color: #e67e22;
  font-weight: 600;
}

.warning-text {
  font-size: 11px;
}

.form-row {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}

button.primary {
  padding: 14px;
  background-color: #27ae60;
  color: white;
  border: none;
  border-radius: 6px;
  font-weight: 600;
  font-size: 16px;
  cursor: pointer;
  transition: all 0.2s;
}

button.primary:hover:not(:disabled) {
  background-color: #229954;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(39, 174, 96, 0.3);
}

button.primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.summary-output {
  margin-top: 24px;
  padding: 20px;
  background: #f8f9fa;
  border: 1px solid #ddd;
  border-radius: 8px;
}

.output-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.output-header h3 {
  margin: 0;
  color: #2c3e50;
}

.output-actions {
  display: flex;
  gap: 8px;
}

.action-btn {
  padding: 6px 12px;
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 13px;
  cursor: pointer;
  transition: all 0.2s;
}

.action-btn:hover:not(:disabled) {
  background: #3498db;
  color: white;
  border-color: #3498db;
}

.action-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.provider-badge {
  display: inline-block;
  padding: 4px 10px;
  background: #e3f2fd;
  color: #1976d2;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 500;
  margin-bottom: 12px;
}

.markdown-output {
  background: white;
  padding: 20px;
  border-radius: 6px;
  line-height: 1.6;
  color: #333;
}

.markdown-output :deep(h1),
.markdown-output :deep(h2),
.markdown-output :deep(h3) {
  margin-top: 16px;
  margin-bottom: 8px;
  color: #2c3e50;
}

.markdown-output :deep(p) {
  margin-bottom: 12px;
}

.markdown-output :deep(ul),
.markdown-output :deep(ol) {
  margin-bottom: 12px;
  padding-left: 24px;
}

.markdown-output :deep(code) {
  background: #f4f4f4;
  padding: 2px 6px;
  border-radius: 3px;
  font-family: 'Monaco', 'Courier New', monospace;
  font-size: 0.9em;
}

.plain-output {
  background: white;
  padding: 16px;
  border-radius: 6px;
  white-space: pre-wrap;
  line-height: 1.6;
  color: #333;
  font-family: 'Georgia', serif;
  font-size: 15px;
}

/* History Modal */
.history-modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.history-modal {
  background: white;
  border-radius: 12px;
  width: 90%;
  max-width: 700px;
  max-height: 80vh;
  display: flex;
  flex-direction: column;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px;
  border-bottom: 1px solid #eee;
}

.modal-header h3 {
  margin: 0;
  color: #2c3e50;
}

.close-btn {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  color: #999;
  padding: 0;
  width: 32px;
  height: 32px;
  border-radius: 4px;
  transition: all 0.2s;
}

.close-btn:hover {
  background: #f3f4f6;
  color: #333;
}

.history-list {
  overflow-y: auto;
  padding: 20px;
  flex: 1;
}

.history-entry {
  padding: 16px;
  background: #f8f9fa;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  margin-bottom: 12px;
}

.history-entry-header h4 {
  margin: 0 0 8px 0;
  color: #2c3e50;
  font-size: 16px;
}

.entry-meta {
  display: flex;
  gap: 8px;
  align-items: center;
  margin-bottom: 12px;
}

.badge {
  display: inline-block;
  padding: 3px 8px;
  background: #e3f2fd;
  color: #1976d2;
  border-radius: 4px;
  font-size: 11px;
  font-weight: 500;
  text-transform: uppercase;
}

.date {
  font-size: 12px;
  color: #999;
  margin-left: auto;
}

.history-entry-actions {
  display: flex;
  gap: 8px;
}

.small-btn {
  padding: 6px 12px;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.small-btn:hover {
  background: #3498db;
  color: white;
  border-color: #3498db;
}

.small-btn.danger:hover {
  background: #e74c3c;
  border-color: #e74c3c;
}

.no-history {
  text-align: center;
  padding: 60px 20px;
  color: #999;
  font-style: italic;
}

@media (max-width: 768px) {
  .form-row {
    grid-template-columns: 1fr;
  }

  .output-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 12px;
  }

  .output-actions {
    width: 100%;
    justify-content: flex-start;
  }
}
</style>
